// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT7XI1hXHcO6ThutPVe84WnQPRl7EaFtI',
    appId: '1:516748094527:web:21e78904f1787cc97b1c8a',
    messagingSenderId: '516748094527',
    projectId: 'pohang-e79be',
    authDomain: 'pohang-e79be.firebaseapp.com',
    databaseURL: 'https://pohang-e79be-default-rtdb.firebaseio.com',
    storageBucket: 'pohang-e79be.appspot.com',
    measurementId: 'G-174VKWNE3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9wtWyYFL_gGykNlGtEXH2JW0x1nlJ-c',
    appId: '1:516748094527:android:047cd878d6ba33f97b1c8a',
    messagingSenderId: '516748094527',
    projectId: 'pohang-e79be',
    databaseURL: 'https://pohang-e79be-default-rtdb.firebaseio.com',
    storageBucket: 'pohang-e79be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRifQbXWq1ZCd4rTdthQp3dEZ_HNhQ9mE',
    appId: '1:516748094527:ios:e1ec7fc790e2864c7b1c8a',
    messagingSenderId: '516748094527',
    projectId: 'pohang-e79be',
    databaseURL: 'https://pohang-e79be-default-rtdb.firebaseio.com',
    storageBucket: 'pohang-e79be.appspot.com',
    androidClientId: '516748094527-505smjh7vv01s0lkabapcn3pqb9q7eeb.apps.googleusercontent.com',
    iosClientId: '516748094527-kgei1jocio4qsa8prn2n9gukti1a4d22.apps.googleusercontent.com',
    iosBundleId: 'com.example.onthewheelpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRifQbXWq1ZCd4rTdthQp3dEZ_HNhQ9mE',
    appId: '1:516748094527:ios:e1ec7fc790e2864c7b1c8a',
    messagingSenderId: '516748094527',
    projectId: 'pohang-e79be',
    databaseURL: 'https://pohang-e79be-default-rtdb.firebaseio.com',
    storageBucket: 'pohang-e79be.appspot.com',
    androidClientId: '516748094527-505smjh7vv01s0lkabapcn3pqb9q7eeb.apps.googleusercontent.com',
    iosClientId: '516748094527-kgei1jocio4qsa8prn2n9gukti1a4d22.apps.googleusercontent.com',
    iosBundleId: 'com.example.onthewheelpractice',
  );
}
